services:
  - type: web
    name: kakwara_hospital
    repo: https://github.com/Otilu/kakwara_hospital
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kakwara-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        value: kakwara-hospital.onrender.com
      - key: PORT
        value: "10000"
      - key: MIX_ENV
        value: prod
      - key: PHX_SERVER
        value: true
      - key: POOL_SIZE
        value: "5"
    healthCheckPath: /health
    plan: free
    region: oregon
    autoDeploy: true
