services:
  - type: web
    name: kakwara_hospital
    runtime: elixir
    repo: https://github.com/Otilu/kakwara_hospital
    branch: main

    buildCommand: >
      MIX_ENV=prod mix deps.get &&
      mix compile &&
      mix assets.deploy &&
      mix release

    startCommand: _build/prod/rel/kakwara_hospital/bin/kakwara_hospital start

    envVars:
      - key: DATABASE_PATH
        value: /etc/kakwara_hospital/kakwara_hospital.db

      - key: SECRET_KEY_BASE
        generateValue: true

      - key: PHX_HOST
        value: kakwara-hospital.onrender.com

      - key: PORT
        value: 10000

      - key: PHX_SERVER
        value: true

    plan: free
    region: oregon
